server:
  port: 8087
  servlet:
    context-path: '/ead-authuser/'


spring:
  application:
    name: ead-authuser-domain-services
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-authuser
    username: postgres
    password: adminpg
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost

resilience4j:
  circuitbreaker:
    instances:
      cb-coursesByUser:
        slidingWindowSize: 30
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 2
        waitDurationInOpenState: 30s
        failureRateThreshold: 80
  retry:
    instances:
      retryInstance:
        maxRetryAttempts: 3
        waitDuration: 5s

ead:
  api:
    url:
      course: 'http://ead-course-domain-services/ead-courses'
  broker:
    exchange:
      userEvent: ead.userevent